
// навбар
export const ACTION_MENU_COLLAPSE = 'ACTION_MENU_COLLAPSE';
export const ACTION_MENU_ITEM = 'ACTION_MENU_ITEM';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';

// авторизация
export const ACTION_IS_AUTH = 'ACTION_IS_AUTH';
export const ACTION_IS_SHOW_MODAL = 'ACTION_IS_SHOW_MODAL';
export const ACTION_CHANGE_LOGIN_INPUT = 'ACTION_CHANGE_LOGIN_INPUT';
export const ACTION_CHANGE_PASSWORD_INPUT = 'ACTION_CHANGE_PASSWORD_INPUT';
export const ACTION_CHANGE_PWT = 'ACTION_CHANGE_PWT';

// journal
export const ACTION_CHANGE_JOURNAL_FILTER_COLLAPSE = 'ACTION_CHANGE_JOURNAL_FILTER_COLLAPSE';