
// навбар
export const ACTION_MENU_COLLAPSE = 'ACTION_MENU_COLLAPSE';
export const ACTION_MENU_ITEM = 'ACTION_MENU_ITEM';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';

// авторизация
export const ACTION_IS_AUTH = 'ACTION_IS_AUTH';
export const ACTION_IS_SHOW_MODAL = 'ACTION_IS_SHOW_MODAL';
export const ACTION_CHANGE_LOGIN_INPUT = 'ACTION_CHANGE_LOGIN_INPUT';
export const ACTION_CHANGE_PASSWORD_INPUT = 'ACTION_CHANGE_PASSWORD_INPUT';
export const ACTION_CHANGE_PWT = 'ACTION_CHANGE_PWT';

// journal
export const ACTION_CHANGE_JOURNAL_FILTER_COLLAPSE = 'ACTION_CHANGE_JOURNAL_FILTER_COLLAPSE';
export const ACTION_CHANGE_DATA_JOURNAL = 'ACTION_CHANGE_DATA_JOURNAL';
export const ACTION_CHANGE_SELECT_ROW_JOURNAL = 'ACTION_CHANGE_SELECT_ROW_JOURNAL';
export const ACTION_CHANGE_JOURNAL_IMAGE = 'ACTION_CHANGE_JOURNAL_IMAGE';
export const ACTION_CHANGE_ZOOM_IMAGE_JOURNAL = 'ACTION_CHANGE_ZOOM_IMAGE_JOURNAL';
export const ACTION_CHANGE_JOURNAL_IMAGE_PROGRESS = 'ACTION_CHANGE_JOURNAL_IMAGE_PROGRESS';
export const ACTION_IS_SHOW_RE_PHOTOGRAPHED_MODAL = 'ACTION_IS_SHOW_RE_PHOTOGRAPHED_MODAL';
export const ACTION_CHANGE_REPHOTO_REASONS_LIST = 'ACTION_CHANGE_REPHOTO_REASONS_LIST';
export const ACTION_CHANGE_REASONS_ITEM = 'ACTION_CHANGE_REASONS_ITEM';
export const ACTION_CHANGE_CLEAN_REASONS_ITEM = 'ACTION_CHANGE_CLEAN_REASONS_ITEM';
export const ACTION_CHANGE_OTHER_REASONS = 'ACTION_CHANGE_OTHER_REASONS';
export const ACTION_CHANGE_STATUS_LIST = 'ACTION_CHANGE_STATUS_LIST';
export const ACTION_CHANGE_SELECT_STATUS = 'ACTION_CHANGE_SELECT_STATUS';
export const ACTION_CHANGE_DATE_FROM_FILTER = 'ACTION_CHANGE_DATE_FROM_FILTER';
export const ACTION_CHANGE_DATE_TO_FILTER = 'ACTION_CHANGE_DATE_TO_FILTER';
export const ACTION_CHANGE_IS_JOURNAL_PROGRESS = 'ACTION_CHANGE_IS_JOURNAL_PROGRESS';
export const ACTION_CHANGE_IS_GET_TASK_BY_KEY_PROGRESS = 'ACTION_CHANGE_IS_GET_TASK_BY_KEY_PROGRESS';
export const ACTION_CHANGE_SET_ORDER_DATA = 'ACTION_CHANGE_SET_ORDER_DATA';

// scan
export const ACTION_IS_GET_ORDER_FROM_WORK = 'ACTION_IS_GET_ORDER_FROM_WORK';
export const ACTION_IS_STOP_GET_ORDER_FROM_WORK_MODAL = 'ACTION_IS_STOP_GET_ORDER_FROM_WORK_MODAL';
export const ACTION_CHANGE_MOVED_FROM = 'ACTION_CHANGE_MOVED_FROM';